language: php
php:
    - '7.1'

before_script:
    - composer install
    - find . -type f -name *.csv -exec chmod 777 {} +
    - chmod 444 tests/integration/CSVTests/InputFiles/EmptyWriteProtected.csv
    - mkdir build

script:
    - phpunit --configuration phpunit.xml.dist

after_script:
    - php vendor/bin/coveralls -v

notifications:
    email: mfmbarber@gmail.com
