language: php
php:
    - '5.6'
    - '7.0'

before_script:
    - composer install
    - find . -type f -name *.csv -exec chmod 777 {} +
    - mkdir build
    
script: 
    - phpunit --configuration phpunit.xml.dist

after_script: 
    - php vendor/bin/coveralls -v

notifications:
    email: mfmbarber@gmail.com
